# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "KvPxgGMNepzrFbRzkMeBSe19nZrlLMMZuYATAKhwZXk+T+KYAtBiP0geBHUY1hbw+ipG3r/WKWwD4rDUu+tSL31nFKpNcKg1jqTYERQ90DNSBvKr+t1OoxMu49IA6Wxdjc45Dw6amNhJqkmmNCrG9GSeNW6N7LItolJHQhJ4mufsmReo2b25qG60gSVrWaoRwgGJ2gnUa4xLJdEg8L1WOTfI76jXAC9V6cLn64Qcfrm4QT6C/Npc8ZyBZIvsFQ9Mh70NTgxT4sG5VlO1c/GA+miC8tdaPX4Sqf5Ma2RqYrqvXa4IbHw21ofov0L5ksj5T3kxlgkKfWc7XWou2hoxmOw4kM/aebAD1BMk1KNKRbnQD6h0upKoyk+6vBewd1FnlnriLerZuxA6zVQ0/Uy8YHX9Sq+xNpTv1PcXC0E0CqwYczKy3jBbx5BDzs4sqUdD4xDlDy/8nlKUWzYLCRQjV03YJF8GEbaVTBZNa1HOwf1XKdGVA01a1T+4GkMbwqirXyXz8UNVMx1DoUerpPXC9A/gG4qmA3W1d3/MnOPE03OPNNlfh5JKTSHZgaVai6XrVkEU7LspL1OPtgMuDL4dmKR59z7Q1/DE9PzaXX3F53zRwkble8k47OzIR9uYGKOssHlMMfHf5gdESbsROuqVhsRJNUHIsxQBJgjza72V/9U="


install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      wget "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
