travis:
  secure:
    BINSTAR_TOKEN: X0SImXRSeOdPNxcfYvr85kx8anJ6HLTKRC8Y7C00hSw73+YK/Y/yhrj2KBfA5pxWvesNC3iMgd+qJoEnVVISJKwkL+VXc84G6qWQhCplqbi8Qi3d0pe5INOv6CM8kaniift5nK58JDcBJlvgRUc8uNWcc7orG/WJ5mh21PuHX6dtoa2HzYH0QsxuPHFs+9QlG6j1sjBdVSatL+CiWP9YVnPbX2iTwmE3c990wJfBOqIyceHwy9SkIGJ837wkP1D99CBWl1c4bw4ABo7rAePOUel+FZ2U3UpmDRNtu318i2H2vFIhfNtEO5wnmCTXUGPDi387Z9VOXAXyww/xLMOuzz+y9kHvTqbgpVTeX8pZTImXEFykSzB7aSAxSp9IqkZrPqJYeCFCAO1c1PsBneBOCXvMh2nhATrPVlgnBm/JaWA2rYllKDlAgkHtC/eRrYk5oYjgQ8ibQPbZEI43B35r4ef5EdCpehLxJw+AtmUt6zrZSbf825SoLbxxQn82d+wnFKsLRI1r+yF9XJlmxO4x+9Mk8IxrP0nWfeeWyN+f+bxx9Vqf5/uvCZUtP1eyIGlzXvVxQ4rbVo2GYkmvD2MvZfeidSE2AGa+xcyZvyBvQCZeKVQWljBPAeIcgd3BYJ5/Q7d6SLGMwVJ8S2aaLCXTiQthOD4Nvnf2DdZdKSlVjm4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
