travis:
  secure:
    BINSTAR_TOKEN: KvPxgGMNepzrFbRzkMeBSe19nZrlLMMZuYATAKhwZXk+T+KYAtBiP0geBHUY1hbw+ipG3r/WKWwD4rDUu+tSL31nFKpNcKg1jqTYERQ90DNSBvKr+t1OoxMu49IA6Wxdjc45Dw6amNhJqkmmNCrG9GSeNW6N7LItolJHQhJ4mufsmReo2b25qG60gSVrWaoRwgGJ2gnUa4xLJdEg8L1WOTfI76jXAC9V6cLn64Qcfrm4QT6C/Npc8ZyBZIvsFQ9Mh70NTgxT4sG5VlO1c/GA+miC8tdaPX4Sqf5Ma2RqYrqvXa4IbHw21ofov0L5ksj5T3kxlgkKfWc7XWou2hoxmOw4kM/aebAD1BMk1KNKRbnQD6h0upKoyk+6vBewd1FnlnriLerZuxA6zVQ0/Uy8YHX9Sq+xNpTv1PcXC0E0CqwYczKy3jBbx5BDzs4sqUdD4xDlDy/8nlKUWzYLCRQjV03YJF8GEbaVTBZNa1HOwf1XKdGVA01a1T+4GkMbwqirXyXz8UNVMx1DoUerpPXC9A/gG4qmA3W1d3/MnOPE03OPNNlfh5JKTSHZgaVai6XrVkEU7LspL1OPtgMuDL4dmKR59z7Q1/DE9PzaXX3F53zRwkble8k47OzIR9uYGKOssHlMMfHf5gdESbsROuqVhsRJNUHIsxQBJgjza72V/9U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
