travis:
  secure:
    BINSTAR_TOKEN: gwU50yCyOv+sl/UKeWJEvHa2urjffuDekOfjy2TC7joiYTWJEokL19cnajW6NDsv6SsVGNKJwuvVOPndw6JP95MVY4vHmpRu7KXz/Dhi/5ssfkLbnl5vZZNRuZeaGuEMQO/xXYhijhZTZQn9/M1eaJVyEWPJOZoukme65r1DXvK2foZp+WwdBIgJN9LO7FhM86qbnYVgw/3b1KhgLrQALw7B9ObTyUH8ThXZkFjLGGCT+tCVd9I65aozjRkwWAqWmVroT+HqVLe56rirM4yyHVlgKssYUfI9k5zsKP4jEUsi3DeixRhwFmmYSyOJ5IHUpq6UKyF3yebTxWBkChjjV7qyV71stde4O9x7Ada2+58xpozAmu/HhberamqOVyot3Z2uIJRCfTSMUAqAllbNQFVwWkzMqIKtebdgKbrD6aXC1dHBlWJ92xKEadl+L+vYz2ORoooBg5QeONN28rI1joOI1GbT9yb6xBT+ZgbOPl/q53juE3qba6MvsWa1cn77HENq4XZESkSCIT+Yn6QlYdeQ9xL7Y/Nz3GPx1cWfgV0T42Nq7EfQ+mJga3ovN3s0o00FgzFl63dJ823hIV8U+5kenDWpyv1hcaVw29V3qczF6Gm4x/umicH0RdbEbXvWeKnAEmtWyAjG5sQw9ou9yf8Bo+3cJc38DLEa7qVneN4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
