travis:
  secure:
    BINSTAR_TOKEN: HFM57DuO4juXcqQgTp4gfX596TA6ELUN5Ylrcg4itblEr4VPJ2fx78ihwcIW1tiM5ipATzlNuAT8laR0p+O9ztZ27FgAX/3cOgYlv2ZyRdu7CVt6No40ETaF6L1/YeF5hs4cDmswt9NmfjOY85uhd12DH6+5feF6nQgMiMNgv40t3d2rL+6xlnaSmF+BqIro0oF5i4hUE7JTXLwER+HJ/j2fOTiYBpn53W3bikOrur0MdngiTX0TqSNBP6r1MRLnv4QDNww5u58Ql34Iw8+eSVwECEiclPj7Ye5r+oYdGKDhOIkjqK4gWL68ESzWa+7HnLp/KhT1zDu3oThkZKS3vwaqEf8HNbvl9W42Nund2yFAV50dpGIwV05GEZYjB2JVgoK71zlzHD8fDPR5pTXB6s9iXuIrse+6/dEBGTXbTmJMLXTbGyIPlAAs0Lou/jm1ZFKG67hPdiWVjQ5Yb7KuXGnQ9WVO9nJhW7z6pjSyTq+UtVw40zCYE3mgA/Apjhh8IrJdyqjMEmGFaRoBXWtrGbnnuTSSqS7i2KyTsqcs9m9UdgMnWlQUumnoYPPyfl+51+wmlIpsXWYF6EcDh42NKNNkPE8r1Yre7qTuuw+Hc8Mwb3WKbuKPKcI7JmZbZuluJt6HCZiKyTsWmvQRC7BkcKX64FKUWo61/bVAPLabcfM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
